// Copyright 2026 Dom Hallan
// SPDX-License-Identifier: Apache-2.0

package logging_test

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/polyglotdev/copyfail-validation/internal/logging"
)

// ExampleNew shows the typical caller pattern: build an Options with
// a captured Writer, invoke New, log a line, and inspect the captured
// JSON. Production callers omit Options.Writer (so logs go to
// os.Stderr) and Options.RunID (so a fresh crypto/rand id is auto-
// generated). The example pins both so godoc can verify exact bytes.
func ExampleNew() {
	buf := &bytes.Buffer{}
	logger := logging.New(logging.Options{
		Writer:    buf,
		RunID:     "00000000000000000000000000000001",
		Verbosity: 1,
	})

	logger.Info("validator started", "host", "example.com")

	var line map[string]any
	_ = json.Unmarshal(buf.Bytes(), &line)

	fmt.Println("level:", line["level"])
	fmt.Println("msg:", line["msg"])
	fmt.Println("run_id:", line["run_id"])
	fmt.Println("host:", line["host"])
	// Output:
	// level: INFO
	// msg: validator started
	// run_id: 00000000000000000000000000000001
	// host: example.com
}

// ExampleOptions shows the field defaults that apply when an
// Options{} zero value is passed to New: Writer becomes os.Stderr,
// RunID is auto-generated by crypto/rand, and Verbosity 0 maps to
// slog.LevelWarn.
func ExampleOptions() {
	opts := logging.Options{}
	fmt.Printf("default verbosity: %d\n", opts.Verbosity)
	fmt.Printf("default run_id: %q\n", opts.RunID)
	fmt.Printf("default writer is nil: %v\n", opts.Writer == nil)
	// Output:
	// default verbosity: 0
	// default run_id: ""
	// default writer is nil: true
}
